### ISSUE TITLE
Adding confirmation when delete iklan

### ISSUE THREAD

**Issue by masaditya** [indent-dev/seller-web#4]
tolong tambahin dialog confirmasi ketika user ingin menghapus iklan, ntar bisa pake component dari `Ant Design` namanyan [Popconfirm ](https://ant.design/components/popconfirm/)

**Comment by syaifuddinzuhri** [comment]
Okay siap mas

**Comment by masaditya** [comment]
> Okay siap mas

Gass poll wkwkw
